name: Deploy to titanic.caltech.edu/~tgorordo

on: push

jobs:
  pandoc_index_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pandoc Compile `index.html`
        uses: docker://pandoc/core:latest
        with:
          args: "--standalone --output=index.html README.md"
      - name: SFTP Upload to `titanic.caltech.edu/tgorordo` in `~/public_html`
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: titanic.caltech.edu
          username: tgorordo
          password: ${{secrets.titanic_password}}
          local_path: ./*
          remote_path: ./public_html
